# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Exit if not on the main branch
      if: endsWith(github.ref, 'main') == false
      run: exit -1
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x


    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        
    - name: Build
      run: dotnet build basic-framework.sln -c Release

    - name: Pack
      run: dotnet pack basic-framework.sln -o tmpnuGet --no-restore

    - name: Display GitVersion config
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        additionalArguments: '/showConfig'
          
